-- MySQL Script generated by MySQL Workbench
-- 12/07/17 14:32:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_paroquia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_paroquia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_paroquia` DEFAULT CHARACTER SET utf8 ;
USE `db_paroquia` ;

-- -----------------------------------------------------
-- Table `db_paroquia`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_paroquia`.`cidade` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_paroquia`.`fiel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_paroquia`.`fiel` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sexo` ENUM('F', 'M') NOT NULL,
  `datanascimento` DATE NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cep` INT(8) NOT NULL,
  `cidade` INT(11) NOT NULL,
  `estadocivil` ENUM('SOLTEIRO(A)', 'CASADO(A)') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fiel_cidade1_idx` (`cidade` ASC),
  CONSTRAINT `fk_fiel_cidade1`
    FOREIGN KEY (`cidade`)
    REFERENCES `db_paroquia`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_paroquia`.`nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_paroquia`.`nivel` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `descricao_UNIQUE` (`descricao` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_paroquia`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_paroquia`.`usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(11) NULL DEFAULT NULL,
  `email` VARCHAR(45) NOT NULL,
  `nivel` INT(11) NOT NULL,
  `ativo` ENUM('S', 'N') NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `nivel`),
  INDEX `fk_usuario_nivel_idx` (`nivel` ASC),
  CONSTRAINT `fk_usuario_nivel`
    FOREIGN KEY (`nivel`)
    REFERENCES `db_paroquia`.`nivel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_paroquia`.`batismo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_paroquia`.`batismo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `batizando` INT(11) NOT NULL,
  `pai` VARCHAR(45) NULL DEFAULT NULL,
  `mae` VARCHAR(45) NULL DEFAULT NULL,
  `padrinho` VARCHAR(45) NOT NULL,
  `madrinha` VARCHAR(45) NOT NULL,
  `datanascimento` DATE NOT NULL,
  `databatismo` DATE NOT NULL,
  `localbatismo` ENUM('Alvorada do Norte') NOT NULL,
  `status` ENUM('P', 'A') NOT NULL,
  `paroco` INT(11) NOT NULL,
  `valor` FLOAT NOT NULL,
  `localnascimento` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_batismo_batizando_idx` (`batizando` ASC),
  INDEX `fk_batismo_localnascimento_idx` (`localnascimento` ASC),
  INDEX `fk_batismo_paroco_idx` (`paroco` ASC),
  CONSTRAINT `fk_batismo_batizando`
    FOREIGN KEY (`batizando`)
    REFERENCES `db_paroquia`.`fiel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_batismo_localnascimento`
    FOREIGN KEY (`localnascimento`)
    REFERENCES `db_paroquia`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_batismo_paroco`
    FOREIGN KEY (`paroco`)
    REFERENCES `db_paroquia`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_paroquia`.`casamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_paroquia`.`casamento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `noivo` INT(11) NOT NULL,
  `noiva` INT(11) NOT NULL,
  `localnascimentonoivo` INT(11) NOT NULL,
  `localnascimentonoiva` INT(11) NOT NULL,
  `datanascimentonoivo` DATE NOT NULL,
  `datanascimentonoiva` DATE NOT NULL,
  `testemunha1` VARCHAR(45) NOT NULL,
  `testemunha2` VARCHAR(45) NOT NULL,
  `datacasamento` DATE NOT NULL,
  `status` ENUM('Pendente', 'Aprovado') NOT NULL,
  `cidade` ENUM('Alvorada do Norte') NOT NULL,
  `valor` FLOAT NOT NULL,
  `paroco` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_noivo_idx` (`noivo` ASC),
  INDEX `fk_noiva_idx` (`noiva` ASC),
  INDEX `fk_local_noivo_idx` (`localnascimentonoivo` ASC),
  INDEX `fk_local_noiva_idx` (`localnascimentonoiva` ASC),
  INDEX `fk_paroco_idx` (`paroco` ASC),
  CONSTRAINT `fk_local_noiva`
    FOREIGN KEY (`localnascimentonoiva`)
    REFERENCES `db_paroquia`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_local_noivo`
    FOREIGN KEY (`localnascimentonoivo`)
    REFERENCES `db_paroquia`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_noiva`
    FOREIGN KEY (`noiva`)
    REFERENCES `db_paroquia`.`fiel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_noivo`
    FOREIGN KEY (`noivo`)
    REFERENCES `db_paroquia`.`fiel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paroco`
    FOREIGN KEY (`paroco`)
    REFERENCES `db_paroquia`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
